export const banks = [
    { id: '0102', name: 'Banco de Venezuela' },
    { id: '0104', name: 'Banco Venezolano de Crédito' },
    { id: '0105', name: 'Banco Mercantil' },
    { id: '0108', name: 'Banco Provincial' },
    { id: '0114', name: 'Bancaribe' },
    { id: '0115', name: 'Banco Exterior' },
    { id: '0128', name: 'Banco Caroní' },
    { id: '0134', name: 'Banesco' },
    { id: '0137', name: 'Banco Sofitasa' },
    { id: '0138', name: 'Banco Plaza' },
    { id: '0146', name: 'Banco De La Gente Emprendedora' },
    { id: '0151', name: 'BFC Banco Fondo Común' },
    { id: '0156', name: '100% Banco' },
    { id: '0157', name: 'Del Sur Banco Universal' },
    { id: '0163', name: 'Banco del Tesoro' },
    { id: '0166', name: 'Banco Agrícola de Venezuela' },
    { id: '0168', name: 'Bancrecer' },
    { id: '0169', name: 'R4, Banco Microfinanciero' },
    { id: '0171', name: 'Banco Activo' },
    { id: '0172', name: 'Bancamiga' },
    { id: '0174', name: 'Banplus' },
    { id: '0175', name: 'Banco Digital De Los Trabajadores' },
    { id: '0177', name: 'Banfanb' },
    { id: '0178', name: 'N58 Banco Digital' },
    { id: '0191', name: 'Banco Nacional de Crédito (BNC)' },
  ];